version: '3'

services:
  fpm_test_article:
    image: php-test:v1
    restart: always
    ports:
      - 83:80 # change ip if required
    volumes:
      - ./nginx_logs:/var/log/nginx/
      - /opt/cms:/usr/share/nginx/html/
